# Generated by Django 4.2.5 on 2023-10-16 07:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid mobile number.')])),
                ('emergency_contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid emergency contact number.')])),
                ('medical_license_number', models.PositiveIntegerField()),
                ('specialty', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=10)),
                ('emergency_contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('room_no', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient')),
            ],
        ),
    ]
