# Generated by Django 4.2.5 on 2023-09-28 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=20)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid mobile number.')])),
                ('emergency_contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid emergency contact number.')])),
                ('medical_license_number', models.CharField(max_length=20)),
                ('specialty', models.CharField(choices=[('General', 'General'), ('Pediatrics', 'Pediatrics'), ('Cardiology', 'Cardiology'), ('Orthopedics', 'Orthopedics'), ('ObstetricsGynecology', 'Obstetrics and Gynecology'), ('Neurology', 'Neurology')], max_length=50)),
                ('availability', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Shifts', 'Shifts')], max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.PositiveIntegerField()),
            ],
        ),
    ]
