# Generated by Django 4.2.5 on 2023-09-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='DB_Doctor',
        ),
    ]
