# Generated by Django 4.2.5 on 2023-09-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_doctor_db_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_doctor',
            name='medical_license_number',
            field=models.IntegerField(max_length=20),
        ),
    ]
