# Generated by Django 4.2.5 on 2023-10-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_bill_patient_paid_bill_patient_pending_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='pending_bill',
            new_name='total_bill',
        ),
    ]
