# Generated by Django 4.2.5 on 2023-09-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_db_doctor_medical_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_doctor',
            name='medical_license_number',
            field=models.PositiveIntegerField(),
        ),
    ]
