# Generated by Django 4.2.5 on 2023-09-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_patient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='DB_Patient',
        ),
    ]
