# Generated by Django 4.2.5 on 2023-09-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_patient_db_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_patient',
            name='emergency_contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='db_patient',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
