# Generated by Django 4.2.5 on 2023-10-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_db_patient_emergency_contact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DB_Doctor',
            new_name='Doctor',
        ),
        migrations.RenameModel(
            old_name='DB_Patient',
            new_name='Patient',
        ),
    ]
